# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'proto/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/service.proto\x12\x07service\x1a\x1bgoogle/protobuf/empty.proto\"N\n\x08Producto\x12\x0e\n\x06\x63odigo\x18\x01 \x01(\t\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\r\n\x05marca\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scripcion\x18\x04 \x01(\t\"\x15\n\x13ProductoListRequest\")\n\x17ProductoRetrieveRequest\x12\x0e\n\x06\x63odigo\x18\x01 \x01(\t2\xb0\x02\n\x12ProductoController\x12;\n\x04List\x12\x1c.service.ProductoListRequest\x1a\x11.service.Producto\"\x00\x30\x01\x12\x30\n\x06\x43reate\x12\x11.service.Producto\x1a\x11.service.Producto\"\x00\x12\x41\n\x08Retrieve\x12 .service.ProductoRetrieveRequest\x1a\x11.service.Producto\"\x00\x12\x30\n\x06Update\x12\x11.service.Producto\x1a\x11.service.Producto\"\x00\x12\x36\n\x07\x44\x65stroy\x12\x11.service.Producto\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTO']._serialized_start=61
  _globals['_PRODUCTO']._serialized_end=139
  _globals['_PRODUCTOLISTREQUEST']._serialized_start=141
  _globals['_PRODUCTOLISTREQUEST']._serialized_end=162
  _globals['_PRODUCTORETRIEVEREQUEST']._serialized_start=164
  _globals['_PRODUCTORETRIEVEREQUEST']._serialized_end=205
  _globals['_PRODUCTOCONTROLLER']._serialized_start=208
  _globals['_PRODUCTOCONTROLLER']._serialized_end=512
# @@protoc_insertion_point(module_scope)
