# Generated by Django 5.0.6 on 2025-05-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_detallepedido_precio_uni_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksucursal',
            name='precio_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
