# Generated by Django 5.0.6 on 2025-05-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_stocksucursal_precio_usd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='precio_uni_usd',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='precio_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
